// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UriShortener.Data.Model;

#nullable disable

namespace UriShortener.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250420125214_Initial-Merged")]
    partial class InitialMerged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UriShortener.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Title = "PremiumUser"
                        },
                        new
                        {
                            Id = 3,
                            Title = "User"
                        });
                });

            modelBuilder.Entity("UriShortener.Data.Entities.ShortenedURI", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("ValidFor")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INT");

                    b.HasKey("Key");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ShortenedURIs", (string)null);
                });

            modelBuilder.Entity("UriShortener.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("JoinedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime?>("EmailVerificationTokenIssuedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("EmailVerificationTokenUsedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime?>("PasswordResetTokenIssuedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("PasswordResetTokenUsedAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pwd")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UriShortener.Data.Entities.UsersRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId","RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("UriShortener.Data.Entities.ShortenedURI", b =>
                {
                    b.HasOne("UriShortener.Data.Entities.User", "Creator")
                        .WithMany("ShortenedURIs")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("UriShortener.Data.Entities.UsersRoles", b =>
                {
                    b.HasOne("UriShortener.Data.Entities.Role", null)
                        .WithMany("UsersRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UriShortener.Data.Entities.User", null)
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UriShortener.Data.Entities.Role", b =>
                {
                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("UriShortener.Data.Entities.User", b =>
                {
                    b.Navigation("ShortenedURIs");

                    b.Navigation("UsersRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
